package gov.ic.silkwave;

public enum DeadLetterTypeEnum {
    INVALID_SOURCE,
    BAD_ENVELOPE,
    NOT_RESOLVABLE,
    NOT_ROUTABLE,
    NOT_DELIVARABLE,
    NOT_AUTHORIZED,
    INVALID_NET_PAYLOAD,
    IMPROPER_CLASSIFICATION,
    UNKNOWN
}
